name: opencv
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
      - streamlit
      - opencv-python
      - Pillow
      - mediapipe
      - streamlit-webrtc
      - pyttsx3
